vistas_to_cityscapes = {
  'construction--barrier--curb':          'sidewalk',
  'construction--barrier--fence':         'fence',
  'construction--barrier--guard-rail':    'fence',
  'construction--barrier--wall':          'wall',
  'construction--flat--bike-lane':        'road',
  'construction--flat--crosswalk-plain':  'road',
  'construction--flat--curb-cut':         'sidewalk',
  'construction--flat--parking':          'road',
  'construction--flat--pedestrian-area':  'sidewalk',
  'construction--flat--rail-track':       'road',
  'construction--flat--road':             'road',
  'construction--flat--service-lane':     'road',
  'construction--flat--sidewalk':         'sidewalk',
  'construction--structure--bridge':      'building',
  'construction--structure--building':    'building',
  'construction--structure--tunnel':      'building',
  'human--person':                        'person',
  'human--rider--bicyclist':              'rider',
  'human--rider--motorcyclist':           'rider',
  'human--rider--other-rider':            'rider',
  'marking--crosswalk-zebra':             'road',
  'marking--general':                     'road',
  'nature--sand':                         'terrain',
  'nature--sky':                          'sky',
  'nature--snow':                         'terrain',
  'nature--terrain':                      'terrain',
  'nature--vegetation':                   'vegetation',
  'object--support--pole':                'pole',
  'object--support--traffic-sign-frame':  'traffic sign',
  'object--support--utility-pole':        'pole',
  'object--traffic-light':                'traffic light',
  'object--traffic-sign--front':          'traffic sign',
  'object--vehicle--bicycle':             'bicycle',
  'object--vehicle--bus':                 'bus',
  'object--vehicle--car':                 'car',
  'object--vehicle--motorcycle':          'motorcycle',
  'object--vehicle--on-rails':            'train',
  'object--vehicle--truck':               'truck',
}


